### ISSUE TITLE
Complete Documentation

### ISSUE THREAD

**Issue by vivekjoshi556** [vivekjoshi556/Checkerz#1]
New Validation Rules Added: Accepted value for checkboxes, (Date Related): IsDate, after, afterOrEqual, before, beforeOrEqual. Add documentation for these rules based on code.

**Comment by triplettpatrick** [comment]
Hello! Is this issue still available? I would like to contribute to it :)

**Comment by vivekjoshi556** [comment]
Yeah sure @triplettpatrick go ahead.

**Comment by vivekjoshi556** [comment]
@triplettpatrick are you still interested in this issue? Do let me know otherwise I will be adding the documentation in next udpate myself.

**Comment by triplettpatrick** [comment]
@vivekjoshi556 Sorry, there were some things that came up which prevented me from giving more priority to the issue. It's best if you continue yourself on the update.

**Comment by vivekjoshi556** [comment]
Fixed in [da6bcc7](https://github.com/vivekjoshi556/Checkerz/commit/da6bcc7c7946e65e59e69c4eff05d2042acf374b).
